# Generated by Django 5.0.3 on 2024-04-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_L', '0002_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='equipo',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
