# Generated by Django 5.0.3 on 2024-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_L', '0004_equipo_usuario_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='categoria',
            field=models.CharField(choices=[('sub_baby', 'Sub Baby'), ('sub_8', 'Sub 8'), ('sub_10', 'Sub 10'), ('sub_11', 'Sub 11'), ('sub_12', 'Sub 12'), ('sub_13', 'Sub 13'), ('sub_14', 'Sub 14'), ('sub_15', 'Sub 15'), ('sub_16', 'Sub 16'), ('ascenso', 'Ascenso'), ('primera', 'Primera'), ('femenina', 'Femenina')], max_length=100, null=True),
        ),
    ]
